In [1]:
import datasets
import pandas as pd

In [14]:
fvapps = datasets.load_dataset("quinn-dougherty/fvapps", split="train")
apps = datasets.load_dataset("codeparrot/apps", split="train")
df = pd.DataFrame(fvapps)
apps_df = pd.DataFrame(apps)

In [5]:
df

,apps_id,apps_question,spec,sorries,apps_difficulty,split
0,2459,"Given an integer, write an algorithm to conver...",def to_hex (n : Int) : String := sorry\n\n/-- ...,6,introductory,train
1,4172,"Given a string, return the minimal number of p...",def solve (s : String) : Int :=\n sorry\n\nde...,10,introductory,train
2,2565,"=====Function Descriptions=====\nIn Python, a ...",def generateLogo (thickness : Nat) : String :=...,5,introductory,train
3,3430,You were given a string of integer temperature...,def lowest_temp (s : String) : Option Int := s...,4,introductory,train
4,1804,There is a secret string which is unknown to y...,def recoverSecret (triplets : List (List Char)...,8,interview,train
...,...,...,...,...,...,...
4707,4067,Bob is preparing to pass IQ test. The most fre...,def iq_test (input : String) : Nat :=\n sorry...,4,introductory,train
4708,2688,# Task\n let F(N) be the sum square of digits ...,def repeat_sequence_len (n : Nat) : Nat :=\n ...,4,introductory,train
4709,3101,Given a list of unique words. Find all pairs o...,def palindrome (s : String) : Bool :=\nsorry\n...,7,introductory,train
4710,3866,Three candidates take part in a TV show.\n\nIn...,structure Candidate where\n name : String\n ...,3,introductory,train
4711,1128,The Chef is given an array of numbers and aske...,def find_balance_point (arr : List Int) : Int ...,7,interview,train

In [6]:
twentythree = df[df.apps_id == "0023"]
twentythree

,apps_id,apps_question,spec,sorries,apps_difficulty,split
48,0023,The only difference between easy and hard vers...,def solve_elections (n : Nat) (voters : List (...,5,interview,train

In [10]:
print(twentythree.apps_question.values[0])

The only difference between easy and hard versions is constraints.

Now elections are held in Berland and you want to win them. More precisely, you want everyone to vote for you.

There are $n$ voters, and two ways to convince each of them to vote for you. The first way to convince the $i$-th voter is to pay him $p_i$ coins. The second way is to make $m_i$ other voters vote for you, and the $i$-th voter will vote for free.

Moreover, the process of such voting takes place in several steps. For example, if there are five voters with $m_1 = 1$, $m_2 = 2$, $m_3 = 2$, $m_4 = 4$, $m_5 = 5$, then you can buy the vote of the fifth voter, and eventually everyone will vote for you. Set of people voting for you will change as follows: ${5} \rightarrow {1, 5} \rightarrow {1, 2, 3, 5} \rightarrow {1, 2, 3, 4, 5}$.

Calculate the minimum number of coins you have to spend so that everyone votes for you.


-----Input-----

The first line contains one integer $t$ ($1 \le t \le 5000$) â€” the number of test cases.

The first line of each test case contains one integer $n$ ($1 \le n \le 5000$) â€” the number of voters.

The next $n$ lines contains the description of voters. $i$-th line contains two integers $m_i$ and $p_i$ ($1 \le p_i \le 10^9, 0 \le m_i < n$).

It is guaranteed that the sum of all $n$ over all test cases does not exceed $5000$.


-----Output-----

For each test case print one integer â€” the minimum number of coins you have to spend so that everyone votes for you.


-----Example-----
Input
3
3
1 5
2 10
2 8
7
0 1
3 1
1 1
6 1
1 1
4 1
4 1
6
2 6
2 3
2 8
2 7
4 4
5 5

Output
8
0
7



-----Note-----

In the first test case you have to buy vote of the third voter. Then the set of people voting for you will change as follows: ${3} \rightarrow {1, 3} \rightarrow {1, 2, 3}$.

In the second example you don't need to buy votes. The set of people voting for you will change as follows: ${1} \rightarrow {1, 3, 5} \rightarrow {1, 2, 3, 5} \rightarrow {1, 2, 3, 5, 6, 7} \rightarrow {1, 2, 3, 4, 5, 6, 7}$.

In the third test case you have to buy votes of the second and the fifth voters. Then the set of people voting for you will change as follows: ${2, 5} \rightarrow {1, 2, 3, 4, 5} \rightarrow {1, 2, 3, 4, 5, 6}$.

In [12]:
print(twentythree.spec.values[0])

def solve_elections (n : Nat) (voters : List (Nat Ã— Nat)) : Nat :=
  sorry

theorem solve_elections_nonnegative (n : Nat) (voters : List (Nat Ã— Nat)) :
  solve_elections n voters â‰¥ 0 :=
sorry

theorem solve_elections_upper_bound (n : Nat) (voters : List (Nat Ã— Nat)) :
  solve_elections n voters â‰¤ List.foldl (Î» acc (pair : Nat Ã— Nat) => acc + pair.2) 0 voters :=
sorry

theorem solve_elections_zero_votes (n : Nat) (voters : List (Nat Ã— Nat)) :
  (List.all voters (Î» pair => pair.1 = 0)) â†’
  solve_elections n voters = 0 :=
sorry

theorem solve_elections_single_zero_vote :
  solve_elections 1 [(0, 5)] = 0 :=
sorry